<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>semantic_mcp_order_shttp_server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- ModelContextProtocol MCP Server SDK -->
    <PackageReference Include="ModelContextProtocol" Version="0.2.0-preview.3" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.2.0-preview.3" />
  </ItemGroup>

</Project>
